### ISSUE TITLE
Apps version

### ISSUE THREAD

**Issue by gutorc92** [labbsr0x/bb-bot#10]
Add a endpoint on bb-bot to add version for apps on format:

/version/app/type_deploy/version

app = name of the app as on /services
type_deploy = env where the app is deployed(dev, homolog, prod, pil)

version = number of the version

**Comment by abilioesteves** [comment]
@gutorc92, shouldn't this info be handled by the bb-manager?

**Comment by gutorc92** [comment]
Bb-bot has the api and bb-manager has the front-end, I will create a issue on bb-manager project as well.
