### ISSUE TITLE
Migrate etcd

### ISSUE THREAD

**Issue by gutorc92** [labbsr0x/bb-bot#19]
Some of our clients need to migrate old promster infra to new ones. It should replace the keys format /app/env-subapp/ip to /service/app-env-subapp/ip. Also, it should be editable by bb-bot API.

**Comment by abilioesteves** [comment]
Could you explain better this need to change to `/service/app-env-subapp/ip`?

How exactly this is organized? `/service` is static, or it gets replaced by something else on runtime? What are `app`, `env` and `subapp`? And why exactly `/app/env-subapp/ip` is not sufficient?

**Comment by gutorc92** [comment]
The bb-bot API stores IPs in ```/service``` prefix so it can separate IPs, versions and app information. As the old infra not use bb-bot API all IPs were registred on ```/``` prefix.  In order to reuse data already registered and keep up to date until old infra still in use, ```/migration ``` router will read all old data then save it using the new pattern.

**Comment by abilioesteves** [comment]
Oh okay. I understand it now. We have added other concepts (not only IPs), so we need to organize them better (with different root paths).

The `/migration` API then needs to be in place, in case anyone have the same problem.

Alright!
