### ISSUE TITLE
Deleting apps with similar names delete more than one app.

### ISSUE THREAD

**Issue by gutorc92** [labbsr0x/bb-bot#26]
if two apps was created named test and test4. They will create the follow keys:

``` /apps/test ```
```/apps/test4```

BB-bot code deletes all keys with prefix:

```await etcd.delete().all().prefix(`${APP_BASE_URL}/${app}`).exec() ```

Deleting app test will create the follow query:

``` await etcd.delete().all().prefix(`apps/test`).exec() ```

As a result, ETCD deletes apps test and test4. 

It should be fix to delete just one key for apps.

**Comment by abilioesteves** [comment]
Agreed, @gutorc92

**Comment by abilioesteves** [comment]
Fixed by #27
