### ISSUE TITLE
Fix security issue

### ISSUE THREAD

**Issue by abilioesteves** [labbsr0x/bb-bot#8]
https://github.com/labbsr0x/bb-bot/network/alert/package-lock.json/minimist/open

**Comment by KarineValenca** [comment]
@abilioesteves this issue is still happening? The link doesn't work.

**Comment by abilioesteves** [comment]
I already fixed the issue :) Thanks @KarineValenca!

**Comment by abilioesteves** [comment]
@KarineValenca, can you access this link: https://github.com/labbsr0x/bb-bot/network/alerts

**Comment by KarineValenca** [comment]
No, this link doesn't work too.

**Comment by abilioesteves** [comment]
Could you please try again?

**Comment by KarineValenca** [comment]
Now it's working.

**Comment by abilioesteves** [comment]
This issue has been fixed already!
